CREATE TABLE `testdb`.`20210696_doctormaster` (
  `doctorid` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `ppsn` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `services` VARCHAR(45) NULL,
  `qualification` VARCHAR(45) NULL,
  `Income` VARCHAR(45) NULL,
  `Address` VARCHAR(45) NULL,
  `Age` VARCHAR(45) NULL,
  `eircode` VARCHAR(45) NULL,
  `createdby` VARCHAR(45) NULL,
  PRIMARY KEY (`doctorid`));
